# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: On-Prem-Hosted-Windows
  vmImage: WIN-DELINEAWS1

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

#- task: Bash@3
#  displayName: start scanning SAST
#  inputs:
#    filePath: ' ~/.fortify/tools/sc-client/22.2.1/bin/scancentral'
#    arguments: '-url $(url_scancentral) start -bt msbuild --build-file IWA.NET.sln -upload -versionid $(versionid) -uptoken $(uptoken) -log sast-$(versionid)-`date +%d-%m-%Y`.log'

#- task: Bash@3
#  displayName: Get Progress scanning
#  inputs:
#    targetType: 'inline'
#    script: |
#      # Write your commands here
#      jobtoken=$(grep "received token" sast-$(versionid)-`date +%d-%m-%Y`.log | awk '(print $6)'
#      echo $jobtoken
      # get status token
#      scancentral -url $(url_scancentral) status -token $jobtoken


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      echo $env:PATH
      scancentral -url $url_scancentral start -bt msbuild --build-file IWA.NET.sln -upload -versionid $versionid -uptoken $uptoken